using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using SeatAllocationOptimizer.Main; // Add namespace for our new classes
using System.Globalization; // For parsing args

// Defines a class for the main operations related to passenger and seat management.
public class MainClass
{
    // Default Constants for plane dimensions
    public const int DefaultPlaneWidth = 6; // Default width
    public const int DefaultPlaneRows = 33; // Default rows (for ~200 seats config)

    // Main entry point for the program
    public static void Main(string[] args)
    {
        // --- Configuration ---
        int planeRows = DefaultPlaneRows;
        int planeWidth = DefaultPlaneWidth;

        if (args.Length >= 2) {
            bool rowsParsed = int.TryParse(args[0], out int parsedRows);
            bool widthParsed = int.TryParse(args[1], out int parsedWidth);
            if (rowsParsed && widthParsed && parsedRows > 0 && parsedWidth > 0) {
                planeRows = parsedRows;
                planeWidth = parsedWidth;
                Console.WriteLine($"Using custom dimensions: Rows={planeRows}, Width={planeWidth}");
            } else {
                Console.WriteLine("Invalid command-line arguments for dimensions. Using defaults.");
                Console.WriteLine("Usage: dotnet run [numberOfRows] [seatsPerRow]");
            }
        } else {
             Console.WriteLine($"Using default dimensions: Rows={planeRows}, Width={planeWidth}");
        }
        // --- End Configuration ---

        // Measure program execution time
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();

        Console.WriteLine("Starting Seating Allocation...");

        // --- New Logic using SeatAllocationOptimizer.Main classes ---

        // 1. Parse Input Data
        string inputFile = "Data/input.txt"; // Input file path
        List<BoardingGroup> boardingGroups = DataParser.ParseInput(inputFile);

        // 2. Configure and run the Allocator
        int rows = planeRows;
        int seatsPerRow = planeWidth;
        var allocator = new SeatingAllocator(planeRows: rows, seatsPerRow: seatsPerRow);

        // 3. Allocate Seats
        SeatingAllocator.AllocationResult result = allocator.AllocateSeats(boardingGroups);

        // 4. Print Results (using Allocator's methods)
        allocator.PrintSeatingMap(); // Prints the map generated by the allocator
        Console.WriteLine($"Total Calculated Revenue: {result.TotalRevenue:C}");
        if (result.UnseatedGroups.Any())
        {
            Console.WriteLine($"Number of unseated groups: {result.UnseatedGroups.Count}");
            // Optionally print details about unseated groups
        }

        // --- End New Logic ---


        // Stop measuring time
        stopwatch.Stop();

        // Print memory usage and time taken
        PrintMemoryUsage(stopwatch);
    }

    // Function to print memory usage - Keep this utility
    public static void PrintMemoryUsage(Stopwatch stopwatch)
    {
        long memoryUsed = GC.GetTotalMemory(false);
        Console.WriteLine($"Memory used: {memoryUsed / 1024} KB");
        Console.WriteLine($"Time taken: {stopwatch.Elapsed}");
    }

    /* --- Removing Old Logic --- */
    // Removed old printMap, calculateRevenue, dataSetupHelper, idealRevenue, processBoardingGroup methods

}

// Note: The original file also had definitions for Passenger, Family, BoardingGroup, BoardingGroupComparator classes.
// These might be defined within this file below the MainClass, or in separate files (e.g., in Entities/).
// If they are in separate files, those files might need to be removed or refactored if they conflict with the new classes.
// For now, we've focused on replacing the logic within MainClass.

